import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='bg-gray-200 p-4'>
          <nav>
            <ul className='flex justify-between'>
              <li>
                <Link href={'/'}>Home</Link>
              </li>
              <li>
                <Link href={'/about'}>About</Link>
              </li>
              <li>
                <Link href={'/contact'}>Contact</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className='h-screen'>{children}</main>
        <footer className='bg-gray-600 text-center'>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
